# Generated by Django 4.2.1 on 2023-06-26 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contacto',
        ),
    ]
