# Generated by Django 4.2.1 on 2023-07-06 04:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0002_remove_producto_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='direccion_cliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='principal.direccioncliente'),
        ),
    ]
